### PR TITLE
1277: remove double quotes from maskWith url() 

### PR DESCRIPTION
**Pull request by HarryFaulkner**
https://github.com/svgdotjs/svg.js/issues/1277

### CODE REVIEW

**Comment by Fuzzyma** [comment]
We have multiple spots with the same Syntax in svg.js. If we change it, we should change it anywhere. e. G. Clip-path.

Also: it seems like you removed the quote all together. Wouldn't it be better to replace it with a single quote instead?

**Comment by HarryFaulkner** [comment]
> We have multiple spots with the same Syntax in svg.js. If we change it, we should change it anywhere. e. G. Clip-path.
> 
> Also: it seems like you removed the quote all together. Wouldn't it be better to replace it with a single quote instead?

**Change it everywhere**
Sure, will add it in the other areas also. 

**Replace quote with single quote**
This is the syntax used by the official documentation, note that there are no inner quotes
`  <circle cx="50" cy="50" r="50" mask="url(#myMask)" />`
[https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask](url)

**Comment by HarryFaulkner** [comment]
Any chance of this getting merged?

**Comment by rossburton** [comment]
This is breaking my SVGs that I want to load into Affinity, so yeah merge please :)

**Comment by Fuzzyma** [comment]
sorry for the long wait. my bad!

**Pull request merged**
