### PR TITLE
Adds yarn installation instructions

### PR DESCRIPTION
**Pull request by waghcwb**

### CODE REVIEW

**Comment by saivan** [comment]
This looks entirely reasonable to me, I don't use yarn, but lets have a look 📦

**Comment by Fuzzyma** [comment]
I always think that yarn people know there stuff and dont need an extra installation instruction. Well - but I guess it wont hurt adding it, right? :D

**Comment by waghcwb** [comment]
@Fuzzyma, done..

**Comment by Fuzzyma** [comment]
Thank you very much!

**Pull request merged**
