### PR TITLE
fix: add Fragment declaration in svg.js.d.ts

### PR DESCRIPTION
**Pull request by we125182**
this pr is to fix issue #1307 .

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Would it make sense to let fragment simply extend from Container to avoid duplication?

**Comment by we125182** [comment]
Actually, I thought in this way. After read source code, find that Container extends Element, but Fragment extends Dom. if Fragment extends Container, it'll has Element methods, but Fragment doesn't have methods of Element

**Comment by Fuzzyma** [comment]
mh, maybe you can add an interface "Containerable" which has all the methods and both fragment and container extend from it

**Comment by we125182** [comment]
I tried the Interface way. But implements `Containerable` Interface, you need define same medthods too. in this way, need define same method three times(`Containerable`, `Fragment`, `Container`). Certanlly use interface can ensure `Container` and 'Frament` has same Constuct Element methods.

image

try on [TS PLAYGROUND](https://www.typescriptlang.org/play?filetype=d.ts#code/CYUwxgNghgTiAEBbA9sArhBByAzgNwHMA6AKxy3gG8AoeeSKHHeAEWUStrvuQDscALjDRgByGAAoAlFzpRgwCSEyIQvAQC54AURVqBUrQIAWASxxcAvtS4MmOves7d484AGFoTCbyiqtgjCmvASG8CbmVjZ0APQxPIgovEggJqjMAGbi8ABiMFAEqk4AZPDufAJQwSAwXMECNRlQYAjl6lW+AEaYztwNgtJavGiInTVRtl7MeQVFAvAgAB4NvMDMbBymiAAOjgLMbZXBUN0IlNaTjAcVHTULy2prDiBz8Fu7L-rX7cenvXT9ASDeDDUZ3OIgkAgYDwUAZaquAgdWTwABeyHYwNBY1qdGs1iAA)

**Comment by we125182** [comment]
I use the dynamic extends to avoid dupliacted declarations. But the temp varibles(ContainableDom, ContainableElement) always export. which means user can import them, actually they didn't exist.  I add comment to explain. Maybe there has a good way.

**Comment by Fuzzyma** [comment]
I don't think anyone will ever import them.
If everything else works like intended I would consider this a good solution :).
Does everything work?

**Comment by we125182** [comment]
Yes, I linked the changed package in a project. `Fragment` has methods of `Containable` and `Dom`. `Container` keep same behavior.
image

**Comment by Fuzzyma** [comment]
Awesome. Thank you!

**Comment by we125182** [comment]
Glad to help.

**Pull request merged**
