### PR TITLE
Tests - HOLD

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This should note be merged until we only see jasmine errors in the travis log.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
@dotnetCarpenter what was this for again? Travis seems to work fine :). Did not try safari and Edge/IE though...

**Comment by dotnetCarpenter** [comment]
I noted that:
>the macOS test vm always disconnect, no matter how much time it's given. Are in contact with saucelabs support, awaiting response.

Perhaps they have fix it since then.

The [relevant browsers we want to run the test suit in](https://github.com/svgdotjs/svg.js/pull/701/files#diff-55490cd00ecc045f3b81f3e85200ed43R28) should be uncommented in _.config/karma.conf.saucelabs.js_. See https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ for possible browsers.

**Comment by Fuzzyma** [comment]
ok got it. thank you!

**Comment by dotnetCarpenter** [comment]
@Fuzzyma I just tried to run the test locally but while Firefox does open, nothing else happens. Are you able to get the test to run locally?

**Comment by Fuzzyma** [comment]
Are you talking about this branch? I didnt test it. However in the master branch tests work and in the 3.0 branch we even moved to headless chrome and headless firefox test which also work great

**Comment by dotnetCarpenter** [comment]
@Fuzzyma Should I try to update this PR, so we can merge it in? If the Sauce Labs test works of course.

**Comment by Fuzzyma** [comment]
Yes that would be great. It would make sense to merge it into 3.0 though...

**Comment by dotnetCarpenter** [comment]
@Fuzzyma I'll take a look and get back to you.

**Comment by dotnetCarpenter** [comment]
Closing this in favor of https://github.com/svgdotjs/svg.js/tree/feature/tests2

**Pull request closed without merging**
