### PR TITLE
Fix typo in type file for Polyline and Marker

### PR DESCRIPTION
**Pull request by Perlkonig**
Applied against 2.x

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Are you sure about that one? I thought Polyline is Polyline and not PolyLine.

**Comment by Perlkonig** [comment]
I'm no expert, as you know!! 😄 

Here's the code that wasn't working:

```typescript
const line = notes.polyline(points.join(" ")).stroke({width: 1.5, color: "black"});
line.marker("end", markerArrow);
line.marker("start", markerCircle);
```

The error was `Property 'marker' does not exist on type 'PolyLine'. Did you mean 'masker'?`.

So I opened the `.d.ts` file and saw that everything was `PolyLine` except for the one that defined `marker()`, so I thought it was a typo and corrected it. Everything compiled fine after that.

**Comment by Fuzzyma** [comment]
Hm okay. To stay consistend, could you rename all occurences to Polyline?

**Comment by Fuzzyma** [comment]
thanks!

**Pull request merged**
