### PR TITLE
#805 Image memory leak fix

### PR DESCRIPTION
**Pull request by kuzmanovicnenad**
Removing image is not removing "load" and "error" events. (+2 events)
Removing image is not removing reference to image in DOM (+1 SVGImageElement detached dom)
This is fixed by passing this.node when registering "load" and "error" events instad of created img element.
Problem was that this.node could not be found in SVG.handlerMap in "off()" method.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Iam not sure why you make it that complicated. Is just `SVG.off(img)` here not working?

```js
SVG.on(img, 'load', function() {
  SVG.off(img)
  //...
})

SVG.on(img, 'error', function(e){
  SVG.off(img)
  //...
}
```

**Comment by kuzmanovicnenad** [comment]
That was the first thing I tried after your comment but it didn't work.

**Comment by Fuzzyma** [comment]
Actually that should work without any problems. So it needs to be checked why this does not work. No need to work around something which would fix the problem in an elegant way.
I really wonder why this does not work. Have to doublecheck that myself

**Comment by kuzmanovicnenad** [comment]
Nice!
Can you please make a new release with the fix?

**Comment by Fuzzyma** [comment]
https://github.com/svgdotjs/svg.js/releases/tag/2.6.4

**Pull request merged**
